if !exists('g:async') | let g:async = {} | endif | let s:async = g:async

inoremap <buffer> \\async-magic <c-r>
noremap  <buffer> \\async-magic :

augroup VIM_ADDON_ASYNC
  au!
  autocmd CmdwinEnter * let g:async.in_cmd = 1
  autocmd CmdwinLeave * let g:async.in_cmd = 0 | call async#RunDelayedActions()
  autocmd WinEnter,InsertLeave * call async#RunDelayedActions()
finish

augroup end

  autocmd BufNewFile * echoe "BufNewFile"
  autocmd BufReadPre * echoe "BufReadPre"
  autocmd BufRead * echoe "BufRead"
  autocmd BufReadPost * echoe "BufReadPost"
  autocmd BufReadCmd * echoe "BufReadCmd"
  autocmd FileReadPre * echoe "FileReadPre"
  autocmd FileReadPost * echoe "FileReadPost"
  autocmd FileReadCmd * echoe "FileReadCmd"
  autocmd FilterReadPre * echoe "FilterReadPre"
  autocmd FilterReadPost * echoe "FilterReadPost"
  autocmd StdinReadPre * echoe "StdinReadPre"
  autocmd StdinReadPost * echoe "StdinReadPost"
  autocmd BufWrite * echoe "BufWrite"
  autocmd BufWritePre * echoe "BufWritePre"
  autocmd BufWritePost * echoe "BufWritePost"
  autocmd BufWriteCmd * echoe "BufWriteCmd"
  autocmd FileWritePre * echoe "FileWritePre"
  autocmd FileWritePost * echoe "FileWritePost"
  autocmd FileWriteCmd * echoe "FileWriteCmd"
  autocmd FileAppendPre * echoe "FileAppendPre"
  autocmd FileAppendPost * echoe "FileAppendPost"
  autocmd FileAppendCmd * echoe "FileAppendCmd"
  autocmd FilterWritePre * echoe "FilterWritePre"
  autocmd FilterWritePost * echoe "FilterWritePost"
  autocmd BufAdd * echoe "BufAdd"
  autocmd BufCreate * echoe "BufCreate"
  autocmd BufDelete * echoe "BufDelete"
  autocmd BufWipeout * echoe "BufWipeout"
  autocmd BufFilePre * echoe "BufFilePre"
  autocmd BufFilePost * echoe "BufFilePost"
  autocmd BufEnter * echoe "BufEnter"
  autocmd BufLeave * echoe "BufLeave"
  autocmd BufWinEnter * echoe "BufWinEnter"
  autocmd BufWinLeave * echoe "BufWinLeave"
  autocmd BufUnload * echoe "BufUnload"
  autocmd BufHidden * echoe "BufHidden"
  autocmd BufNew * echoe "BufNew"
  autocmd SwapExists * echoe "SwapExists"
  autocmd FileType * echoe "FileType"
  autocmd Syntax * echoe "Syntax"
  autocmd EncodingChanged * echoe "EncodingChanged"
  autocmd TermChanged * echoe "TermChanged"
  autocmd VimEnter * echoe "VimEnter"
  autocmd GUIEnter * echoe "GUIEnter"
  autocmd TermResponse * echoe "TermResponse"
  autocmd VimLeavePre * echoe "VimLeavePre"
  autocmd VimLeave * echoe "VimLeave"
  autocmd FileChangedShell * echoe "FileChangedShell"
  autocmd FileChangedShellPost * echoe "FileChangedShellPost"
  autocmd FileChangedRO * echoe "FileChangedRO"
  autocmd ShellCmdPost * echoe "ShellCmdPost"
  autocmd ShellFilterPost * echoe "ShellFilterPost"
  autocmd FuncUndefined * echoe "FuncUndefined"
  autocmd SpellFileMissing * echoe "SpellFileMissing"
  autocmd SourcePre * echoe "SourcePre"
  autocmd SourceCmd * echoe "SourceCmd"
  autocmd VimResized * echoe "VimResized"
  autocmd FocusGained * echoe "FocusGained"
  autocmd FocusLost * echoe "FocusLost"
  autocmd CursorHold * echoe "CursorHold"
  autocmd CursorHoldI * echoe "CursorHoldI"
  autocmd CursorMoved * echoe "CursorMoved"
  autocmd CursorMovedI * echoe "CursorMovedI"
  autocmd WinEnter * echoe "WinEnter"
  autocmd WinLeave * echoe "WinLeave"
  autocmd TabEnter * echoe "TabEnter"
  autocmd TabLeave * echoe "TabLeave"
  autocmd CmdwinEnter * echoe "CmdwinEnter"
  autocmd CmdwinLeave * echoe "CmdwinLeave"
  autocmd InsertEnter * echoe "InsertEnter"
  autocmd InsertChange * echoe "InsertChange"
  autocmd InsertLeave * echoe "InsertLeave"
  autocmd ColorScheme * echoe "ColorScheme"
  autocmd RemoteReply * echoe "RemoteReply"
  autocmd QuickFixCmdPre * echoe "QuickFixCmdPre"
  autocmd QuickFixCmdPost * echoe "QuickFixCmdPost"
  autocmd SessionLoadPost * echoe "SessionLoadPost"
  autocmd MenuPopup * echoe "MenuPopup"
